DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS cargo;
DROP TABLE IF EXISTS perfil;
 
CREATE TABLE cargo (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NOME VARCHAR(250) NOT NULL
);

CREATE TABLE perfil (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL
);

CREATE TABLE user (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL,
	CPF VARCHAR(250) NOT NULL,
	SEXO VARCHAR(250) NOT NULL,
	DATA_DE_NASCIMENTO DATE NOT NULL,
	CARGO_ID VARCHAR(250) NOT NULL,
	PERFIL_ID VARCHAR(250) NOT NULL,
	ACTIVE BIT NOT NULL,
  FOREIGN KEY (CARGO_ID) REFERENCES cargo(ID),
  FOREIGN KEY (PERFIL_ID) REFERENCES perfil(ID)
);
 
INSERT INTO cargo (nome) VALUES
  ('Gerente'),
  ('Supervisor'),
  ('Administrativo');

INSERT INTO perfil (nome) VALUES
  ('Administrador'),
  ('Comum');